packages:
- .

flags:
  snap-server:
    openssl: true

extra-deps:
- aeson-1.2.4.0
- base-noprelude-4.10.1.0
- bifunctors-5.5.2
- bizzlelude-1.1.0
- containers-0.5.11.0
- directory-1.3.2.1
- lens-4.16
- monad-logger-0.3.28.1
- persistent-2.8.1
- persistent-postgresql-2.8.1.1
- resourcet-1.1.11
- text-1.2.3.0
- time-1.8.0.1
- transformers-0.5.5.0
- validation-1

resolver: lts-10.1
