packages:
- .

extra-deps:
- base-noprelude-4.10.1.0
- bizzlelude-1.1.0
- directory-1.3.1.5
- heist-1.0.1.1
- map-syntax-0.2.0.2
- persistent-2.7.3
- snap-1.0.0.2
- snap-cors-1.2.11
- time-1.8.0.3
- transformers-0.5.5.0

resolver: lts-10.1
